package com.fcant.shop.mapper;

import com.fcant.shop.bean.AttentionShop;
import org.apache.ibatis.annotations.Mapper;

/**
 * AttentionShopMapper
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 16:09 2019-09-17/0017
 */
@Mapper
public interface AttentionShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String attentionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(AttentionShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(AttentionShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    AttentionShop selectByPrimaryKey(String attentionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(AttentionShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(AttentionShop record);
}