package com.fcant.shop.mapper;

import com.fcant.shop.bean.OrderPay;
import org.apache.ibatis.annotations.Mapper;

/**
 * OrderPayMapper
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 16:09 2019-09-17/0017
 */
@Mapper
public interface OrderPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String orderPayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    OrderPay selectByPrimaryKey(String orderPayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(OrderPay record);
}