package com.fcant.shop.mapper;

import com.fcant.shop.bean.OrderShop;

public interface OrderShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String orderShopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(OrderShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(OrderShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    OrderShop selectByPrimaryKey(String orderShopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(OrderShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(OrderShop record);
}