package com.fcant.shop.mapper;

import com.fcant.shop.bean.OrderBasic;

public interface OrderBasicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_basic
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String oederId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_basic
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(OrderBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_basic
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(OrderBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_basic
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    OrderBasic selectByPrimaryKey(String oederId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_basic
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(OrderBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_basic
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(OrderBasic record);
}