package com.fcant.shop.mapper;

import com.fcant.shop.bean.ShopType;
import org.apache.ibatis.annotations.Mapper;

/**
 * ShopTypeMapper
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 16:10 2019-09-17/0017
 */
@Mapper
public interface ShopTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_type
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String shopTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_type
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_type
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_type
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    ShopType selectByPrimaryKey(String shopTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_type
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_type
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(ShopType record);
}