package com.fcant.shop.mapper;

import com.fcant.shop.bean.Shop;
import org.apache.ibatis.annotations.Mapper;

/**
 * ShopMapper
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 16:10 2019-09-17/0017
 */
@Mapper
public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    Shop selectByPrimaryKey(String shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(Shop record);
}