package com.fcant.shop.mapper;

import com.fcant.shop.bean.Shop;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    Shop selectByPrimaryKey(String shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_shop
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(Shop record);
}