package com.fcant.shop.bean;

public class AttentionShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_shop.attention_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String attentionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_shop.user_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_shop.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_shop.attention_id
     *
     * @return the value of attention_shop.attention_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getAttentionId() {
        return attentionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_shop.attention_id
     *
     * @param attentionId the value for attention_shop.attention_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setAttentionId(String attentionId) {
        this.attentionId = attentionId == null ? null : attentionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_shop.user_id
     *
     * @return the value of attention_shop.user_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_shop.user_id
     *
     * @param userId the value for attention_shop.user_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_shop.shop_id
     *
     * @return the value of attention_shop.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_shop.shop_id
     *
     * @param shopId the value for attention_shop.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }
}