package com.fcant.shop.bean;

import java.util.Date;

public class Board {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_board.board_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_board.board_title
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String boardTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_board.board_content
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String boardContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_board.board_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Date boardTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_board.board_id
     *
     * @return the value of sh_board.board_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_board.board_id
     *
     * @param boardId the value for sh_board.board_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_board.board_title
     *
     * @return the value of sh_board.board_title
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getBoardTitle() {
        return boardTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_board.board_title
     *
     * @param boardTitle the value for sh_board.board_title
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setBoardTitle(String boardTitle) {
        this.boardTitle = boardTitle == null ? null : boardTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_board.board_content
     *
     * @return the value of sh_board.board_content
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getBoardContent() {
        return boardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_board.board_content
     *
     * @param boardContent the value for sh_board.board_content
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setBoardContent(String boardContent) {
        this.boardContent = boardContent == null ? null : boardContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_board.board_time
     *
     * @return the value of sh_board.board_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Date getBoardTime() {
        return boardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_board.board_time
     *
     * @param boardTime the value for sh_board.board_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setBoardTime(Date boardTime) {
        this.boardTime = boardTime;
    }
}