package com.fcant.shop.bean;

import lombok.Data;

import java.util.Date;

/**
 * OrderPay
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 23:18 2019-09-16/0016
 */
@Data
public class OrderPay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_pay_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String orderPayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_basic_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String orderBasicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_status
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Integer payStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_pay_id
     *
     * @return the value of order_pay.order_pay_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getOrderPayId() {
        return orderPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_pay_id
     *
     * @param orderPayId the value for order_pay.order_pay_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setOrderPayId(String orderPayId) {
        this.orderPayId = orderPayId == null ? null : orderPayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_basic_id
     *
     * @return the value of order_pay.order_basic_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getOrderBasicId() {
        return orderBasicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_basic_id
     *
     * @param orderBasicId the value for order_pay.order_basic_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setOrderBasicId(String orderBasicId) {
        this.orderBasicId = orderBasicId == null ? null : orderBasicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_time
     *
     * @return the value of order_pay.pay_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_time
     *
     * @param payTime the value for order_pay.pay_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_status
     *
     * @return the value of order_pay.pay_status
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_status
     *
     * @param payStatus the value for order_pay.pay_status
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }
}