package com.fcant.shop.bean;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.shop_name
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.original_price
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Double originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.current_price
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Double currentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.stock_num
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Integer stockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.shop_photo
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String shopPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_shop.shop_type_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String shopTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.shop_id
     *
     * @return the value of sh_shop.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.shop_id
     *
     * @param shopId the value for sh_shop.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.shop_name
     *
     * @return the value of sh_shop.shop_name
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.shop_name
     *
     * @param shopName the value for sh_shop.shop_name
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.original_price
     *
     * @return the value of sh_shop.original_price
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Double getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.original_price
     *
     * @param originalPrice the value for sh_shop.original_price
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setOriginalPrice(Double originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.current_price
     *
     * @return the value of sh_shop.current_price
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Double getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.current_price
     *
     * @param currentPrice the value for sh_shop.current_price
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.stock_num
     *
     * @return the value of sh_shop.stock_num
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.stock_num
     *
     * @param stockNum the value for sh_shop.stock_num
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.shop_photo
     *
     * @return the value of sh_shop.shop_photo
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getShopPhoto() {
        return shopPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.shop_photo
     *
     * @param shopPhoto the value for sh_shop.shop_photo
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopPhoto(String shopPhoto) {
        this.shopPhoto = shopPhoto == null ? null : shopPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_shop.shop_type_id
     *
     * @return the value of sh_shop.shop_type_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getShopTypeId() {
        return shopTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_shop.shop_type_id
     *
     * @param shopTypeId the value for sh_shop.shop_type_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopTypeId(String shopTypeId) {
        this.shopTypeId = shopTypeId == null ? null : shopTypeId.trim();
    }
}