package com.fcant.shop.bean;

import lombok.Data;

import java.util.Date;

/**
 * ShopCart
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 23:19 2019-09-16/0016
 */
@Data
public class ShopCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.cart_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.shop_num
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Integer shopNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.user_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.create_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.cart_id
     *
     * @return the value of shop_cart.cart_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.cart_id
     *
     * @param cartId the value for shop_cart.cart_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setCartId(String cartId) {
        this.cartId = cartId == null ? null : cartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.shop_id
     *
     * @return the value of shop_cart.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.shop_id
     *
     * @param shopId the value for shop_cart.shop_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.shop_num
     *
     * @return the value of shop_cart.shop_num
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Integer getShopNum() {
        return shopNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.shop_num
     *
     * @param shopNum the value for shop_cart.shop_num
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setShopNum(Integer shopNum) {
        this.shopNum = shopNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.user_id
     *
     * @return the value of shop_cart.user_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.user_id
     *
     * @param userId the value for shop_cart.user_id
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.create_time
     *
     * @return the value of shop_cart.create_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.create_time
     *
     * @param createTime the value for shop_cart.create_time
     *
     * @mbg.generated Mon Sep 16 23:13:05 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}